### ISSUE TITLE
[REQUEST]Update mockups

### ISSUE THREAD

**Issue by thewinger** [MengTo/Angle-Sketch-Plugin#20]
An action that will detect all mockups applied and updates them with the same artboard.

**Comment by MengTo** [comment]
That's a good feature!

**Comment by mikeprecious** [comment]
Hey @MengTo as the Angle Sketch plugin exists today, if I generate a mock-up with Angle and then go back and modify the artwork in the source Artboard, should Angle automatically detect the changes on the Artboard, and update the Angle generated mock-up?

**Comment by thewinger** [comment]
@mikeprecious not right now I think. But it would be a nice feature
