### ISSUE TITLE
An action that will insert artboards from different page

### ISSUE THREAD

**Issue by ndastur** [MengTo/Angle-Sketch-Plugin#23]
As per the comment on spectrum. A small suggestion. I created my app mockups on a different page than the website mockups. But wanted to place an app screen in the website artboards using your phone template. CMD+Backslash does an auto-detect. But it would be nice if there was an action that showed the choice popup and allowed the user to select the artboard to insert.

**Comment by tmergulhao** [comment]
Hey @ndastur.

If you are using the latest version of Angle, that is already possible.

Thanks!
