### ISSUE TITLE
Apply Mockup and other functions not working

### ISSUE THREAD

**Issue by mlibres** [MengTo/Angle-Sketch-Plugin#24]
I have updated to Sketch 49.1 and downloaded and installed Angle Library and the plugin, yet nothing happens when I press Command + \ or manually click in the toolbar. The "Plugin" heading highlights, but nothing pops up or occurs. Help please! 

I have a screen recording, but it won't allow me to attach it.

**Comment by MengTo** [comment]
Can you try to install High Sierra and tell us if you manage to get it to work?

Meng

**Comment by 3raxton** [comment]
I run on High Sierra and can confirm this does not fix the problem.

**Comment by tmergulhao** [comment]
Hello @mlibres,

Do you have a contact e-mail I could use to address the issues?
