### ISSUE TITLE
Screen: Choose image works but apply mockup does not

### ISSUE THREAD

**Issue by mill3rtime** [MengTo/Angle-Sketch-Plugin#26]
I follow the tutorial and neither the keyboard shortcut or the "apply mockup" from the plugin menu does anything. Overrides>screen>choose image works

**Comment by tmergulhao** [comment]
Hey @mill3rtime. This seems to be a problem with how Angle is interacting with your system. Do you have an email to which I can send a message to follow up on the issue?

Thanks
