### ISSUE TITLE
Support for El Capitan 10.11.6

### ISSUE THREAD

**Issue by teamdarkpanda** [MengTo/Angle-Sketch-Plugin#27]
Add support for Mac OSX **El Capitan 10.11.6**

**Comment by tmergulhao** [comment]
Hey @teamdarkpanda 

https://github.com/MengTo/Angle-Sketch-Plugin/releases/tag/v1.1.2

😄

**Comment by dH3s1** [comment]
@tmergulhao That appears to be a dead link. The most recent version I can see is v1.1.0 and this still doesn't have El Capitan 10.11.6 support.

**Comment by dH3s1** [comment]
Ah, just seen the code changes, I see the plug-in only has maximum compatibility with version 49.3. I'll try to update Sketch and try again.

**Comment by dH3s1** [comment]
@tmergulhao I've now updated Sketch to v50 and can confirm that the plug-in doesn't work on El Capitan 10.11.6. Hopefully this can be resolved.

**Comment by tmergulhao** [comment]
Hello @dH3s1.
What version of Angle Plugin and Sketch are you currently using?

The latest version of Angle is 1.1.1. It's available on [releases](https://github.com/MengTo/Angle-Sketch-Plugin/releases)

**Comment by dH3s1** [comment]
@tmergulhao The version update you posted a couple of hours ago (v1.1.1) done the trick. All working fine now! Thank you so much for the fast resolve.
