### ISSUE TITLE
QA: auto update 

### ISSUE THREAD

**Issue by mikeprecious** [MengTo/Angle-Sketch-Plugin#28]
Hey @MengTo as the Angle Sketch plugin exists today, if I generate a mock-up with Angle and then go back and modify the artwork in the source Artboard, should Angle automatically detect the changes on the Artboard, and automatically update the Angle generated mock-up?

**Comment by tmergulhao** [comment]
It is indeed a useful feature, @mikeprecious.

This functionality is on the roadmap of development, but we cannot guarantee dates as this is not an issue that impedes Angle's use. As the project is open-source, pull requests are always welcome.

**Comment by mikeprecious** [comment]
Hi @tmergulhao @MengTo I'll assume by your response, the feature, as I described it, does not yet exist in Angle. 

If not, definitely would be a highly useful feature. Given Angle is for showcasing existing-generated screen design artwork, there is typically changes that happen to the original screen designs as they progress through concept, production, or roadmap-related versions. Having the Angle-generated instance auto-update as the original Artboard's content changes, would be great! 

Thanks for your work on this Sketch plugin.

**Comment by mikeprecious** [comment]
@tmergulhao @MengTo I've been a repeated paid user of the Angle mock-up kits. Wondering if a more robust version of the Angle Sketch plugin with a [Magic Mirror-esque] auto update feature would be in the cards for a paying user.

**Comment by tmergulhao** [comment]
Hi @mikeprecious,

Thanks for the support, you made Angle for Sketch possible!

We want to provide the best product for our consumers and, regardless of it, provide a good plugin for the community at large. Nonetheless, the target for the 1.0 version of Angle for Sketch was to provide the necessary features to work with the Angle Library. We will continue supporting Angle's stability for the time being.
