### ISSUE TITLE
Ignore artboards

### ISSUE THREAD

**Issue by tyburrowbridge** [MengTo/Angle-Sketch-Plugin#32]
Love the plugin, but would really like a way to ignore artboards.

Here is the use case: 
1. creating loads of mockups & variations
2. would only like to pick from a few mockups to apply angle's to
3. currently the dropdown populates all artboards (which in my current file is 30+)

Cheers, and thanks for considering the feature request.

**Comment by tyburrowbridge** [comment]
@tmergulhao - maybe giving artboards a naming convention would allow a user to hide them. 

add "//" to artboard name to hide from list.

IE - "// Login Screen"

**Comment by tmergulhao** [comment]
@tyburrowbridge Actually, this is a good idea. I'd totally use that for symbols and stuff. Going to put it on my bucket list…

Would you be happy with the convention being: ignore anything that begins with a **\**?

**Comment by tyburrowbridge** [comment]
I personally would be fine with \. You rock for making this happen. 

👊
