### ISSUE TITLE
Unable to install Angle.sketchplugin

### ISSUE THREAD

**Issue by kyleabens** [MengTo/Angle-Sketch-Plugin#33]
I downloaded the Full Angle 2 Sketch Plugin and when I unzip it, Angle.sketchplugin is a folder and isn't any sort of application I can launch to install the plugin.  How can I install it?

<img width="208" alt="screen shot 2018-08-29 at 3 07 16 pm" src="https://user-images.githubusercontent.com/25699262/44810022-70c5e500-ab9e-11e8-99ff-db5d4a6dbaa8.png">

**Comment by thomaswangio** [comment]
https://github.com/MengTo/Angle-Sketch-Plugin/archive/master.zip

**Comment by kyleabens** [comment]
Figured out that I needed to download Sketch first.  Sorry very new to this.
