### ISSUE TITLE
[Bug] Not working in 51.3 (57544)

### ISSUE THREAD

**Issue by raphaelloder** [MengTo/Angle-Sketch-Plugin#36]
The recent update seems to have broken Angle for older versions (specifically 51.3).

When trying to apply a mockup to any shape, the toast says

> There seems to be an issue with the shape we are trying to apply.

MacBook Pro (2017)
macOS Mojave (10.14)

**Comment by tmergulhao** [comment]
Thanks for the report @raphaelloder . Problems such as these are expected. Can you please tell which mockup you are having trouble with? Is this happening to all of them or just some of them?

**Comment by sampeniak** [comment]
@tmergulhao getting the same error. Plugin won't work on any mockup :(

**Comment by raphaelloder** [comment]
I'm not quite sure what you mean by "which mockup"? 

I have a generic shape (Rectangle, Rounded Rectangle, Oval, etc) I'm trying to apply a generic artboard to.
But upon selecting _Apply mockup_ it shows the error toast and I can't choose my artboard, which I was able to before this bug.

**Comment by himynameisubik** [comment]
Having the same issue here. Every mockup I try to apply an Artboard to just shows the "There seems to be an issue with the shape we are trying to apply." message. Might be a OS X Mojave problem?

**Comment by tmergulhao** [comment]
@himynameisubik @raphaelloder @sampeniak can you please download 1.1.2 from https://github.com/MengTo/Angle-Sketch-Plugin/releases while I investigate the issue?

**Comment by himynameisubik** [comment]
@tmergulhao Thanks for the reply, although applying does work on 1.1.2 the artboard names are totally mixed up.

**Comment by sampeniak** [comment]
@tmergulhao 1.1.2 is working for me. I'm not getting the same artboard name bug as @himynameisubik  though.
