### ISSUE TITLE
Configurable Shortcut Key

### ISSUE THREAD

**Issue by jhildenbiddle** [MengTo/Angle-Sketch-Plugin#38]
The CMD+\ shortcut is also the default shortcut for [1Password](https://1password.com/). 

Given how popular 1Password is and the frequency with which it is used compared to Angle, I'd much prefer to change the keyboard shortcut for Angle than 1Password.

Thx!

**Comment by tmergulhao** [comment]
Hey @jhildenbiddle. You can use the custom shortcuts feature from macOS. Go to System Preferences, Keyboard and Shortcuts
