### ISSUE TITLE
Angle Plugin does not work on Sketch Version 72

### ISSUE THREAD

**Issue by justinxcarter** [MengTo/Angle-Sketch-Plugin#63]
Just updated to Sketch 72 and the Angle plugin doesn't appear to work anymore in this version.  
Using Angle 1.1.5 with the newest update of Angle Library (May 2021)

Any plans on updating this soon?

Thanks!
Jusitn

**Comment by jiarongkoh** [comment]
I'm encountering the same problem too

**Comment by nofuchsgiven** [comment]
Same here, does not work Sketch 72 (124316).

**Comment by markgeyer** [comment]
Same. You can work around it with forward-facing device shots by exporting an image and loading it manually, though angle device shots ignore the screen layer perspective altogether. Love this plugin but the last commit was from 11 months ago.

**Comment by Samaing1983** [comment]
Hello,

This is Sam from Design+Code.

I did some testing and it seems that the latest version 72 of Sketch is not compatible anymore with our Angle plugin 1.1.5.
If you wish to use our plugin, I would suggest that you work with Sketch 71.2 for now as it is working with Angle 1.1.5. Our team is currently working on updating the plugin.

Sorry about the inconvenience and thank you for your understanding.

The Design+Code Team 😀

**Comment by Samaing1983** [comment]
Hello,

Our team have updated the Angle plugin for Sketch 72 +. It will be version 1.1.6.

https://github.com/MengTo/Angle-Sketch-Plugin/releases/download/v1.1.6/Angle.sketchplugin.zip

Thank you.
The Design+Code Team 😀

**Comment by justinxcarter** [comment]
Thank you guys so much!
